export const databaseTable = `
    CREATE TABLE IF NOT EXISTS power_data (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER,
    HOUR INTEGER,
    MINUTE INTEGER,
    SECOND INTEGER,
    APC TEXT,
    DATE TEXT,
    HOSTNAME TEXT,
    VERSION TEXT,
    UPSNAME TEXT,
    CABLE TEXT,
    DRIVER TEXT,
    UPSMODE TEXT,
    STARTTIME TEXT,
    MODEL TEXT,
    STATUS TEXT,
    LINEV REAL,
    LOADPCT REAL,
    BCHARGE REAL,
    TIMELEFT REAL,
    MBATTCHG INTEGER,
    MINTIMEL INTEGER,
    MAXTIME INTEGER,
    SENSE TEXT,
    LOTRANS REAL,
    HITRANS REAL,
    ALARMDEL TEXT,
    BATTV REAL,
    LASTXFER TEXT,
    NUMXFERS INTEGER,
    TONBATT INTEGER,
    CUMONBATT INTEGER,
    XOFFBATT TEXT,
    SELFTEST TEXT,
    STATFLAG TEXT,
    SERIALNO TEXT,
    BATTDATE TEXT,
    NOMINV REAL,
    NOMBATTV REAL,
    NOMPOWER INTEGER,
    FIRMWARE TEXT,
    END_APC TEXT
    )
`;

export const preparedJson = `{
    "YEAR": null,
    "MONTH": null,
    "DAY": null,
    "HOUR": null,
    "MINUTE": null,
    "SECOND": null,
    "APC": null,
    "DATE": null,
    "HOSTNAME": null,
    "VERSION": null,
    "UPSNAME": null,
    "CABLE": null,
    "DRIVER": null,
    "UPSMODE": null,
    "STARTTIME": null,
    "MODEL": null,
    "STATUS": null,
    "LINEV": null,
    "LOADPCT": null,
    "BCHARGE": null,
    "TIMELEFT": null,
    "MBATTCHG": null,
    "MINTIMEL": null,
    "MAXTIME": null,
    "SENSE": null,
    "LOTRANS": null,
    "HITRANS": null,
    "ALARMDEL": null,
    "BATTV": null,
    "LASTXFER": null,
    "NUMXFERS": null,
    "TONBATT": null,
    "CUMONBATT": null,
    "XOFFBATT": null,
    "SELFTEST": null,
    "STATFLAG": null,
    "SERIALNO": null,
    "BATTDATE": null,
    "NOMINV": null,
    "NOMBATTV": null,
    "NOMPOWER": null,
    "FIRMWARE": null,
    "END_APC": null
}`;

export const prepareDataInsert = `
    INSERT INTO power_data VALUES(
    null,
    :YEAR,
    :MONTH,
    :DAY,
    :HOUR,
    :MINUTE,
    :SECOND,
    :APC,
    :DATE,
    :HOSTNAME,
    :VERSION,
    :UPSNAME,
    :CABLE,
    :DRIVER,
    :UPSMODE,
    :STARTTIME,
    :MODEL,
    :STATUS,
    :LINEV,
    :LOADPCT,
    :BCHARGE,
    :TIMELEFT,
    :MBATTCHG,
    :MINTIMEL,
    :MAXTIME,
    :SENSE,
    :LOTRANS,
    :HITRANS,
    :ALARMDEL,
    :BATTV,
    :LASTXFER,
    :NUMXFERS,
    :TONBATT,
    :CUMONBATT,
    :XOFFBATT,
    :SELFTEST,
    :STATFLAG,
    :SERIALNO,
    :BATTDATE,
    :NOMINV,
    :NOMBATTV,
    :NOMPOWER,
    :FIRMWARE,
    :END_APC
    )
`;
